# Generated by Django 4.0.3 on 2022-05-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='members.specialties'),
        ),
    ]
