# Generated by Django 4.0.3 on 2022-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_patient_disease_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='disease',
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B-', 'B-'), ('B+', 'B+'), ('O+', 'O+'), ('O-', 'O-'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, null=True),
        ),
    ]
