# Generated by Django 4.0.3 on 2022-05-22 21:58

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consaltations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_symptoms', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('is_reconsult', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.specialties')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('re_prescription_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('consult_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.consaltations')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.doctor')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.patient')),
            ],
        ),
    ]
