# Generated by Django 4.0.3 on 2022-06-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_patient_disease_alter_patient_blood_and_more'),
        ('pages', '0002_consaltations_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consaltations',
            old_name='Photo',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='consaltations',
            name='is_reconsult',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('consultation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.consaltations')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.doctor')),
                ('pati', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.patient')),
            ],
        ),
    ]
