# Generated by Django 4.0.3 on 2022-06-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_photo_consaltations_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consaltations',
            name='history',
        ),
        migrations.RemoveField(
            model_name='consaltations',
            name='is_reconsult',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='re_prescription_date',
        ),
    ]
