# Generated by Django 4.0.3 on 2022-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consaltations',
            name='photo',
            field=models.ImageField(blank=True, upload_to='consultation_image/'),
        ),
    ]
